import 'package:flutter/material.dart';


import 'package:flutter/cupertino.dart';
import 'package:invoicegenerator/model.dart';


List<ProductModal> productList = [
  ProductModal(
      id: 1,
      name: 'Adidas Shoes',
      price: 899.99,
      img: 'assets/img/adidas_pro_1.jpeg',
      category: 'Sports',
      discount: 10,
      quantity: 1),
  ProductModal(
      name: 'Adidas_pro',
      price: 499.99,
      img: 'assets/img/adidas_pro_2.jpg',
      category: 'Sports',
      discount: 5,
      id: 2,
      quantity: 1),
  ProductModal(
      name: 'Adidas_pro3',
      price: 59.99,
      img: 'assets/img/adidas_pro_3.jpg',
      category: 'Sports',
      discount: 15,
      id: 3,
      quantity: 1),
  ProductModal(
      name: 'Adidas_pro4',
      price: 39.99,
      img: 'assets/img/adidas_pro_4.jpg',
      category: 'Sports',
      discount: 10,
      id: 4,
      quantity: 1),
  ProductModal(
      name: 'HeadPhone',
      price: 299.99,
      img: 'assets/img/beat_h.png',
      category: 'Electronics',
      discount: 20,
      id: 5,
      quantity: 1),
  ProductModal(
      name: 'BoatHeadphone',
      price: 199.99,
      img: 'assets/img/Beats wireless dre studio.png',
      category: 'Electronics',
      discount: 10,
      id: 6,
      quantity: 1),
  ProductModal(
      name: 'BlueTooth',
      price: 79.99,
      img: 'assets/img/blue_tooth.png',
      category: 'Electronics',
      discount: 12,
      id: 7,
      quantity: 1),
  ProductModal(
      name: 'Boat s3 Headphone',
      price: 29.99,
      img: 'assets/img/boat.png',
      category: 'Electronics',
      discount: 8,
      id: 8,
      quantity: 1),
  ProductModal(
      name: 'Camera',
      price: 19.99,
      img: 'assets/img/camera.png',
      category: 'Electronics',
      discount: 15,
      id: 9,
      quantity: 1),
  ProductModal(
      name: 'Canon camera',
      price: 149.99,
      img: 'assets/img/canon.png',
      category: 'Electronics',
      discount: 5,
      id: 10,
      quantity: 1),
  ProductModal(
      name: 'FujiFilm camera',
      price: 129.99,
      img: 'assets/img/fujifilm.png',
      category: 'Electronics',
      discount: 7,
      id: 11,
      quantity: 1),
  ProductModal(
      name: 'Game Remote',
      price: 24.99,
      img: 'assets/img/game reamote.png',
      category: 'Electronics',
      discount: 10,
      id: 12,
      quantity: 1),
  ProductModal(
      name: 'S2 Headphone',
      price: 3.99,
      img: 'assets/img/h_phone 2.png',
      category: 'Electronics',
      discount: 3,
      id: 13,
      quantity: 1),
  ProductModal(
      name: 'S3 HeadPhone',
      price: 5.99,
      img: 'assets/img/h_phone3.png',
      category: 'Electronics',
      discount: 4,
      id: 14,
      quantity: 1),
  ProductModal(
      name: 'S4 HeadPhone',
      price: 89.99,
      img: 'assets/img/h_phone 4.png',
      category: 'Electronics',
      discount: 6,
      id: 15,
      quantity: 1),
  ProductModal(
      name: 'H1 HeadPhone',
      price: 24.99,
      img: 'assets/img/head_phone.png',
      category: 'Electronics',
      discount: 8,
      id: 16,
      quantity: 1),
  ProductModal(
      name: 'Puma Shoes',
      price: 49.99,
      img: 'assets/img/img_27.png',
      category: 'Sports',
      discount: 10,
      id: 17,
      quantity: 1),
  ProductModal(
      name: 'Puma Sport',
      price: 129.99,
      img: 'assets/img/img_28.png',
      category: 'Sports',
      discount: 5,
      id: 18,
      quantity: 1),
  ProductModal(
      name: 'Puma Shoes',
      price: 799.99,
      img: 'assets/img/img_29.png',
      category: 'Sports',
      discount: 15,
      id: 19,
      quantity: 1),
  ProductModal(
      name: 'Puma_Ware',
      price: 699.99,
      img: 'assets/img/img_30.png',
      category: 'Sports',
      discount: 10,
      id: 20,
      quantity: 1),
  ProductModal(
      name: 'Puma_1',
      price: 14.99,
      img: 'assets/img/img_31.png',
      category: 'Sports',
      discount: 12,
      id: 21,
      quantity: 1),
  ProductModal(
      name: 'Smart Watch',
      price: 39.99,
      img: 'assets/img/img_32.png',
      category: 'Electronics',
      discount: 8,
      id: 22,
      quantity: 1),
  ProductModal(
      name: 'I Phone',
      price: 79.99,
      img: 'assets/img/iphone.png',
      category: 'Electronics',
      discount: 10,
      id: 23,
      quantity: 1),
  ProductModal(
      name: 'Laptop',
      price: 59.99,
      img: 'assets/img/laptop _2.png',
      category: 'Electronics',
      discount: 7,
      id: 24,
      quantity: 1),
  ProductModal(
      name: 'HP Laptop',
      price: 9.99,
      img: 'assets/img/laptop_1.png',
      category: 'Electronics',
      discount: 4,
      id: 25,
      quantity: 1),
  ProductModal(
      name: 'LED',
      price: 29.99,
      img: 'assets/img/LED.png',
      category: 'Electronics',
      discount: 6,
      id: 26,
      quantity: 1),
  ProductModal(
      name: 'Mic',
      price: 19.99,
      img: 'assets/img/mic.png',
      category: 'Electronics',
      discount: 5,
      id: 27,
      quantity: 1),
  ProductModal(
      name: 'Mouse',
      price: 24.99,
      img: 'assets/img/mouse.png',
      category: 'Electronics',
      discount: 7,
      id: 28,
      quantity: 1),
  ProductModal(
      name: 'Movie Camera',
      price: 99.99,
      img: 'assets/img/movie_camera.png',
      category: 'Electronics',
      discount: 10,
      id: 29,
      quantity: 1),
  ProductModal(
      name: 'Poards',
      price: 14.99,
      img: 'assets/img/poards.png',
      category: 'Electronics',
      discount: 6,
      id: 30,
      quantity: 1),
  ProductModal(
      name: 'Redmie',
      price: 2.49,
      img: 'assets/img/redmi.png',
      category: 'Electronics',
      discount: 2,
      id: 31,
      quantity: 1),
  ProductModal(
      name: 'Nike_Sports',
      price: 1.99,
      img: 'assets/img/shoes.png',
      category: 'Sports',
      discount: 3,
      id: 32,
      quantity: 1),
  ProductModal(
      name: 'Nike2',
      price: 2.99,
      img: 'assets/img/shoes 4.png',
      category: 'Sports',
      discount: 4,
      id: 33,
      quantity: 1),
  ProductModal(
      name: 'Nike Shoes',
      price: 3.99,
      img: 'assets/img/shoes 5.png',
      category: 'Sports',
      discount: 5,
      id: 34,
      quantity: 1),
  ProductModal(
      name: 'Nike3',
      price: 1.29,
      img: 'assets/img/shoes 6.png',
      category: 'Sports',
      discount: 3,
      id: 35,
      quantity: 1),
  ProductModal(
      name: 'Nike4',
      price: 4.99,
      img: 'assets/img/shoes 7.png',
      category: 'Sports',
      discount: 6,
      id: 36,
      quantity: 1),
  ProductModal(
      name: 'Nike5',
      price: 5.99,
      img: 'assets/img/shoes 8.png',
      category: 'Sports',
      discount: 7,
      id: 37,
      quantity: 1),
  ProductModal(
      name: 'Nike6',
      price: 7.99,
      img: 'assets/img/shoes 9.png',
      category: 'Sports',
      discount: 8,
      id: 38,
      quantity: 1),
  ProductModal(
      name: 'Classic Watch',
      price: 19.99,
      img: 'assets/img/watch_1.png',
      category: 'Electronics',
      discount: 10,
      id: 39,
      quantity: 1),
  ProductModal(
      name: 'Classic Watch+',
      price: 79.99,
      img: 'assets/img/watch_2.png',
      category: 'Electronics',
      discount: 15,
      id: 40,
      quantity: 1),
  ProductModal(
      name: 'Apple',
      price: 90.10,
      img: 'assets/img/apple.jpeg',
      category: 'Fruits',
      discount: 10,
      id: 41,
      quantity: 1),
  ProductModal(
      name: 'Banana',
      price: 10.99,
      img: 'assets/img/banana.jpeg',
      category: 'Fruits',
      discount: 12,
      id: 42,
      quantity: 1),
  ProductModal(
      name: 'Burger',
      price: 25.79,
      img: 'assets/img/Burger.jpeg',
      category: 'Food',
      discount: 5,
      id: 43,
      quantity: 1),
  ProductModal(
      name: 'Grapes',
      price: 95.98,
      img: 'assets/img/grapes.jpeg',
      category: 'Fruits',
      discount: 60,
      id: 44,
      quantity: 1),
  ProductModal(
      name: 'Pizza',
      price: 58.36,
      img: 'assets/img/Pizza.jpeg',
      category: 'Food',
      discount: 25,
      id: 45,
      quantity: 1),
  ProductModal(
      name: 'Puma_sports',
      price: 85.38,
      img: 'assets/img/shoes_3.png',
      category: 'Sports',
      discount: 25,
      id: 46,
      quantity: 1),
  ProductModal(
      name: 'Sandwich',
      price: 85.38,
      img: 'assets/img/sandwich.jpeg',
      category: 'Food',
      discount: 5,
      id: 47,
      quantity: 1),
  ProductModal(
      name: 'MOMOS',
      price: 50.32,
      img: 'assets/img/MOMs.jpeg',
      category: 'Food',
      discount: 2,
      id: 48,
      quantity: 1),
  ProductModal(
      name: 'Pasta',
      price: 101.32,
      img: 'assets/img/pasta.jpeg',
      category: 'Food',
      discount: 9,
      id: 49,
      quantity: 1),
  ProductModal(
      name: 'Pani Puri',
      price: 10.32,
      img: 'assets/img/panipuri.jpg',
      category: 'Food',
      discount: 9,
      id: 50,
      quantity: 1),
  ProductModal(
      name: 'Strawberries',
      price: 90.00,
      img: 'assets/img/Strawberry.jpg',
      category: 'Fruits',
      discount: 50,
      id: 51,
      quantity: 1),
  ProductModal(
      name: 'Mango',
      price: 120.00,
      img: 'assets/img/MAngo.jpeg',
      category: 'Fruits',
      discount: 20,
      id: 52,
      quantity: 1),
  ProductModal(
      name: 'Orange',
      price: 70.17,
      img: 'assets/img/Orange.jpeg',
      category: 'Fruits',
      discount: 5,
      id: 53,
      quantity: 1),
  ProductModal(
      name: 'WaterMelon',
      price: 50.17,
      img: 'assets/img/WaterMelon.jpeg',
      category: 'Fruits',
      discount: 2,
      id: 54,
      quantity: 1),
  ProductModal(
      name: 'Cherries',
      price: 20.00,
      img: 'assets/img/Cherry.jpeg',
      category: 'Fruits',
      discount: 8,
      id: 55,
      quantity: 1),
];

TextEditingController txtName= TextEditingController();
TextEditingController txtMobileNum= TextEditingController();
TextEditingController txtEmail= TextEditingController();
TextEditingController txtAddress= TextEditingController();

//for show
List showItemsList = [];

//for add
List addItems = [];

double payment() {
  double ans = 0;
  for (int i = 0; i < addItems.length; i++) {
    ans = ans + addItems[i].price;
  }
  return ans += (ans * 18) / 100;
}